SetUserFTA .rar Soup
SetUserFTA .tar Soup
::SetUserFTA .zip Soup
SetUserFTA .7z Soup
SetUserFTA .gz Soup
SetUserFTA .tgz Soup
SetUserFTA .7zip Soup
SetUserFTA .zlib Soup
SetUserFTA .7-zip Soup
SetUserFTA .z Soup